apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: pokeapp-deployment 
spec: 
  selector: 
    matchLabels: 
      app: PokeApp
  template: 
    metadata: 
      labels: 
        app: PokeAapp 
    spec: 
      containers: 
      - name: pokeapp1 
        image:  mateocolombo/pokeapp:1.1.2
        ports: 
        - containerPort: 9898 
--- 
apiVersion: v1 
kind: Service 
metadata: 
  name: pokeapp-service
spec: 
  ports: 
    - port: 80 
      targetPort: 9898 
      nodePort: 30001 
  selector: 
    app: PokeApp
  type: LoadBalancer 
