apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: pokeapp-army
  namespace: mateo-pokeapp-dev
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      app: PokeApp
  template: 
    metadata: 
      labels: 
        app: PokeApp 
    spec: 
      containers: 
      - name: pokeapp-container 
        image:  mateocolombo/pokeapp:1.1.2
        ports: 
        - containerPort: 4402
--- 
apiVersion: v1 
kind: Service 
metadata: 
  name: pokeapp-service
  namespace: mateo-pokeapp-dev
spec: 
  ports: 
      port: 80
      targetPort: 4402 
      nodePort: 30002
  selector: 
    app: PokeApp
  type: LoadBalancer 
