apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: pokeapp-deployment 
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      app: PokeApp
  template: 
    metadata: 
      labels: 
        app: PokeApp 
    spec: 
      containers: 
      - name: pokeapp1 
        image:  mateocolombo/pokeapp:1.1.2
        ports: 
        - containerPort: 80
--- 
apiVersion: v1 
kind: Service 
metadata: 
  name: pokeapp-service
spec: 
  ports: 
    - port: 8080 
      targetPort: 80 
      nodePort: 30002
  selector: 
    app: PokeApp
  type: LoadBalancer 
