apiVersion: networking.k8s.io/v1 
kind: Ingress 
metadata: 
  name: mateo-ingress 
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    -  "mateo.modelodevops.sociuschile.cl" 
    secretName: pokeapp-tls-secret
  rules:
  - host: pokeapp.example.com 
  rules: 
    - host: "mateo.modelodevops.sociuschile.cl" 
      http: 
        paths: 
          - backend: 
              service: 
                name: pokeapp-service
                port: 
                  number: 8080
            path: / 
            pathType: Prefix 
