name: Deploy-Kubernetes
on:
  pull_request:
    branches: [master]
  push:
    branches: [develop]

jobs:
  Build-And-Push:
    runs-on: ubuntu-latest
    env:
      container_name: pokeapp_web
      image_name: pokeapp
      tag_image: lts
      container_port: 80

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '19.7.0'

      - name: Install Dependencies
        run: npm install

      - name: Build Docker Image
        run: docker build -t ${{ env.image_name }}:${{ env.tag_image }} --file dockerfile .

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker Image
        run: |
          docker tag ${{ env.image_name }}:${{ env.tag_image }} mateocolombo/pokeapp:${{ env.tag_image }}
          docker push mateocolombo/pokeapp:${{ env.tag_image }}

  Push-To-Kubernetes:
    runs-on: ubuntu-latest
    needs: ["Build-And-Push"]
    env:
      CLUSTER_TOKEN: ${{ secrets.CLUSTER_TOKEN }}
      POKEAPP_KEY: ${{ secrets.POKEAPP_KEY }}
      POKEAPP_CRT: ${{ secrets.POKEAPP_CRT }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '19.7.0'
      
      - name: Install
        run: npm install

      - name: Update Kubernetes Secrets
        run: |
          sed -i 's|_pokeapp_key_|${{ secrets.POKEAPP_KEY }}|g' kustomize/secret.yaml --debug
          sed -i 's|_pokeapp_crt_|${{ secrets.POKEAPP_CRT }}|g' kustomize/secret.yaml --debug  

      - name: Azure Login
        run: |
          kubectl config set-cluster ModeloDevops-AKS --server=https://modelodevops-aks-dns-b137e13a.hcp.westeurope.azmk8s.io
          kubectl config set-context ModeloDevops-AKS-Admin --cluster=ModeloDevops-AKS --namespace=mateo-pokeapp-dev 
          kubectl config set clusters.ModeloDevops-AKS.certificate-authority-data LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUU2RENDQXRDZ0F3SUJBZ0lRVnoxR0ZRZ1M0QVhtWmNjV2NrYlZyREFOQmdrcWhraUc5dzBCQVFzRkFEQU4KTVFzd0NRWURWUVFERXdKallUQWdGdzB5TWpBMk1EWXlNalUwTURsYUdBOHlNRFV5TURZd05qSXpNRFF3T1ZvdwpEVEVMTUFrR0ExVUVBeE1DWTJFd2dnSWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUNEd0F3Z2dJS0FvSUNBUUR5CkVVNUo1bG16dFVOK1RnVWozWG5MSlZCWTVjeklocDllVExMR1IyYWdFNUN4TXhoZVc4d0h1d251WC9hQWFkbFQKcThncU1NdGVudzA4WlMxbWtzUHJkaUNpZU8ramtMa0gyajdtb21VUmt3WkVldXl1bUVxOHhralVqcFUweUs2NAo3bTRlcTh6U2ZLRld3SDIyOFJnOG5LYm1mbnRibkJ1cWFndTlzdm5IK3pJL2VINWxhWHhoYklyWVBTYXJDMXBaCnQyeStFd3p1R1BoNkZtaWYva2VyaDIwMzh2NGdpRlZFSTJFN0VaTlFTcklKZTRPMU5lWnFyUTFIQjNHZExmWEEKbDdqNTlTcFBiaWpZNkQ5MDJKb2kycStmUXBMRjFDcXkyQlhqdVphWm1kb091UXVMM3I0aTFnWGMyMHpTMkR5awp1TkhFbkpxdHJ3djIweTRDelF4OWJMV3FWRjVNemVhd0R0WWxjN2ZESCtLTUtoZmZYM3lmZmZka3ZiZWtieW9JCkMwWHBrcjZZc05uMXVPWWVmSGMzZmhEWWNUVTdVdWxMRG1jVGlydEJVS0cvdHk1UTV4NjFLaUdrUTUvV2tSM2cKZk9ZWjIxdkNEellKRTJubWdBRmJEaWROZTNmVmlZYWJtVGVQVm5UYkJqUjFFaGN2OGJNSytmRmZsSzh4UU1MRQpUa2dqZFFVYXJJaDkxUUZRVWpub2dRQ2dudjZQVFlPblN2bVI4a09QbnU5Z3NmNVRxb3RXN1hmWGR2NmFObmNvCmVDV1FkK2IxWVlLM0svemx1T1VZSWpGS2h3aWxrSVNNamJIMm1vSnVzY0FNejZxSm83NkwzeGU1WURUZnhVMDgKdnhPMmVRenBoRTlEUGdkYmNXM1lwVHRwcTdnZk5IeUdWcVJ0ZzJBY1V3SURBUUFCbzBJd1FEQU9CZ05WSFE4QgpBZjhFQkFNQ0FxUXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVVIWndnMDNsT1ZhcXVENC8zCkRWWnFuWXkzMWUwd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dJQkFDcDFtNGRKcnh3ZlBoRkN0Z0lnQkxxZWNaa2wKY3ZPempJZFpPa29PME90Qm9UcGR1bmp2WWx6ZEY3Z2RUUHI4Z0pSc2VRamQ1SHNnT1puTWhydEROMXJXcUp6aQo4ODluc3FreXpibmViaTJ4TjljR0ZKTERocGdRblB4c2lFS2VNMHpaengxS3BiL2R0aFhzL1dMQ0dJSWdORkhYCmR0WFdQZWs1MCtZVHU1dDU5cjVrNHBSZGppblRmMUpoRjEydjZpVkIzK3JyOEJTbmJPZW4xN08rZk9uTXJrWmgKN09uYUVDTVpQRFpQQnBvZURkanlOM3VJU3lpRWxMdGJPaUtzTUNMWEZVNW9WQ3czVGk5SVpEaldHVlVZaHlNOQp0MHlzU05XTzZ4ZUJFQkMrZk1zSzkwTGRsU2pwZWpWSVduUUlJUC9vVnpOcjVLL3JtSEdTQzJWRDYvYXgyRGVECmRwOStwQU1rVVdUSlhBanFDNXErZHVydGpKazdSZ0hVdXdFcytadFNBVlQyOGZQNUpaVkpWSUFZZjErUjZNeUkKdTlDOWs5NWxuMUJEelJqMWRuR3Fjc1RJbk1teW80VWV2R2VhMFVzams5ZS9KNDA2ZDY5MjlhRlF6MWN4RFI4dgpSNGZLTzJRbTNaRkZvV1B5a0tnL0g5eThZQjVDT1RwT2svWXZkWlBTUlpVeFJHVHVoNjJDdXl0RE9waDNwakY5ClA1NzBlQVJEVVBxTC9UTjRzL0l2UFFaTFFVbDZZT3k0cDhZN3VUSmlISXJRZGJLUWF1NjlMRC9sa09UeER3R0kKRnBvK3hlaXc3dGJ6NGp2Q3d5b0lROFdMUnlrZVhaMndsZzJ0RFh1ZG5XQk4rNXJ0c09KNnhqWGg3SnJETmNBbApnbFQ3NlhuUlRmWGUwV1ZSCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
          kubectl config set-credentials mateo --token=${{ secrets.CLUSTER_TOKEN }} 
          kubectl config set-context ModeloDevops-AKS-Admin --user=mateo
          kubectl config use-context ModeloDevops-AKS-Admin
          kubectl apply -k kustomize
         

